event-listener.name=watsonx.data-listener

juicyray.queryevent.log.queryCreatedEvent=true
juicyray.queryevent.log4j2.configLocation=/opt/presto/etc/log4j-events.properties
juicyray.queryevent.clustername=presto
juicyray.queryevent.log.splitCompletedEvent=false
juicyray.queryevent.log.queryOptimizerEvent=true

AUDITSCHEMA  = https
AUDITSERVICE = zen-audit-svc
AUDITPORT    = 9880
NAMESPACE    = cpd-instance

watsonx.queryevent.filter.enabled=false
watsonx.queryevent.filter.keyword=qhmm
watsonx.queryevent.filter.catalogs=tpch
watsonx.queryevent.filter.schemas=tpch.sf1

mysql.service.enabled=false
audit.service.enabled=false

#Open telemetry configs
tracing-enabled=false
exporter-endpoint=http://localhost:4317
max-exporter-batch-size=256
max-queue-size=1024
schedule-delay=1000
exporter-timeout=1024
trace-sampling-ratio=1.0

#CES Kafka configs
guardium-enabled=false
guardium-event-kafka-topic=123.lakehouse.audit_events
kafka-brokers=ibm-lh-lakehouse-ces-0.cpd-instance.apps.ares-db2.cp.fyre.ibm.com:443,ibm-lh-lakehouse-ces-1.cpd-instance.apps.ares-db2.cp.fyre.ibm.com:443,ibm-lh-lakehouse-ces-2.cpd-instance.apps.ares-db2.cp.fyre.ibm.com:443
finops-enabled=true
finops-event-kafka-topic=lakehouse.workload_event
